name: CI

on: 
  push: 
    branches: [main]
  pull_request: 
    branches: [main]

jobs:
  build:
    strategy: 
      matrix:
        node-version: [20.x, 22.6]
  
    name: Build with ${{matrix.node-version}}
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
          cache: npm
      - run: npm ci
      - run: npm run build
    
  test: 
      strategy:
        matrix:
          node-version: [20.x]
      
      name: Run all tests
      runs-on: ubuntu-latest

      steps: 
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: Use Node.js ${{matrix.node-version}}
          uses: actions/setup-node@v3
          with:
            node-version: ${{matrix.node-version}}
            cache: npm
        - run: npm ci

        - name: Build Next.js for E2E tests
          run: npm run build
          env:
            SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        
        - name: Linter
          run: npm run lint
        
        - name: Run unit tests
          run: npm run test -- --coverage
        
        - name: Install Playwright (used for Storybook and E2E tests)
          run: npx playwright install --with-deps  
        
        